---
title: "EDA"
output: github_document
date: "2025-10-02"
---

```{r setup, include=FALSE}
library(p8105.datasets)
library(tidyverse)

weather_df = 
  weather_df |>
  mutate(
    month = lubridate::floor_date(date, unit = "month"))

```

make plots
```{r}
weather_df |> 
    ggplot(aes(x = prcp)) + 
  geom_histogram()
```

check on extreme values
```{r}
weather_df |> 
  filter(prcp>1000)
```

look at data again
```{r}
weather_df |> 
  filter(tmax>=20, tmax <=30) |> 
  ggplot(aes(x=tmin, y=tmax, color=name, shape = name))+
  geom_point()
```
## add groups
```{r}
weather_df |> 
  group_by(month)
```
Group and count things
```{r}
weather_df |> 
  group_by(name) |> 
  summarize(
    n=n()
  )
```

```{r}
weather_df |> 
  group_by(month) |> 
  summarize(
    n=n()
  )
```

```{r}
weather_df |> 
  group_by(month, name) |> 
  summarize(
    n=n()
  )
```
```{r}

weather_df |> 
  group_by(month) |> 
  summarize(
    n=n_distinct(date)
  )
```
You can count directly
```{r}
weather_df |> 
  count(name)
```
Add more interesting summaries

```{r}

weather_df |> 
  group_by(name, month) |> 
  summarize(
    mean_tmax=mean(tmax, na.rm=TRUE),
    median_tmin=median(tmin, na.rm=TRUE),
    sd_prcp=sd(prcp,na.rm=TRUE)
  )
```

```{r}
weather_df |> 
  group_by(name, month) |> 
  summarize(mean_tmax=mean(tmax, na.rm=TRUE)) |> 
  ggplot(aes(x=month,y=mean_tmax, color=name))+ 
  geom_point() +
  geom_line()

```
Sometimes format 
```{r}

weather_df |> 
  group_by(name, month) |> 
  summarize(mean_tmax=mean(tmax, na.rm=TRUE)) |> 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax
  ) |> 
  knitr::kable(digits = 2)

```

## mutate with groups
```{r}
weather_df |> 
  group_by(name) |> 
  mutate(
    mean_tmax=mean(tmax, na.rm=TRUE),
    center_tmax=tmax-mean_tmax
  ) |> 
  ggplot(aes(x=date,y=center_tmax, color=name))+
  geom_point()

```

look for cold days.
```{r}
weather_df |> 
  group_by(name,month) |> 
  mutate(temp_rank=min_rank(desc(tmax))) |> 
  filter(temp_rank<2)
```

what about lags?
```{r}

weather_df |> 
  mutate(lag_tmax=lag(tmax))
```


use the variables you create
```{r}
weather_df |> 
  group_by(name) |> 
  mutate(
    temp_change=tmax-lag(tmax) )|> 
      summarize(ch_rank=min_rank(temp_change)), na.rm = TRUE)
                tmax_c_max=max(temp_change, na.rm=TRUE) |> 
  filter(desc(ch_rank)<2
  )
                
```


