---
title: "viz 2"
output: github_document
date: "2025-09-30"
---


/*install.packages("viridis") devtools::install_github("p8105/p8105.datasets") */
```{r}

library(viridis)
library(tidyverse)
library(patchwork)
library(p8105.datasets)

```

```{r}
library(p8105.datasets)
data("weather_df")
```



```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5)
```

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    color = "Location",
    caption = "Data from the rnoaa package"
  )
```

```{r}
weather_df |> 
  filter(tmax>10, tmax<30) |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    color = "Location",
    caption = "Data from the rnoaa package") + 
  scale_x_continuous(
    breaks = c(-15, 0, 15), 
    labels = c("-15ºC", "0", "15"),
    limits = c(-20, 30)) + 
  viridis::scale_color_viridis(
    name = "Location", 
    discrete = TRUE
  )
```
## theme

make my base plot
```{r}
ggp_temperature= weather_df |> 
  filter(tmax>10, tmax<30) |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    color = "Location",
    caption = "Data from the rnoaa package") + 
  scale_x_continuous(
    breaks = c(-15, 0, 15), 
    labels = c("-15ºC", "0", "15"),
    limits = c(-20, 30)) + 
  viridis::scale_color_viridis(
    name = "Location", 
    discrete = TRUE
  )

```

update it 


```{r}
ggp_temperature+
  theme_minimal()+
  theme(legend.position = "bottom")
```

## adding data in geoms
```{r}
central_park_df=
  weather_df |> 
  filter(name=="CentralPark_NY")

molokai_park_df=
  weather_df |> 
  filter(name=="Molokai_HI")


ggplot(data=molokai_park_df, aes(x=date,y=tmax, color= name))+
  geom_point()+
  geom_line(data=central_park_df)
```
## `patchwork`


make three plots and combien using patchwork
```{r}
ggp_tmax_tmin=
  weather_df |> 
  ggplot(aes(x = tmax, y = tmin, color = name)) + 
  geom_point(alpha = .5) +
  theme(legend.position = "none")

prcp_dens_p = 
  weather_df |> 
  filter(prcp > 0) |> 
  ggplot(aes(x = prcp, fill = name)) + 
  geom_density(alpha = .5) + 
  theme(legend.position = "none")


tmax_date_p = 
  weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  theme(legend.position = "bottom")


(ggp_tmax_tmin + prcp_dens_p) / tmax_date_p

```
## data manipulation

```{r}
weather_df |>
  mutate(name = forcats::fct_relevel(name, c("Molokai_HI", "CentralPark_NY", "Waterhole_WA"))) |> 
  ggplot(aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), color = "blue", alpha = .5) + 
  theme(legend.position = "bottom")

```



```{r}
weather_df |>
  mutate(name = forcats::fct_reorder(name, tmax)) |> 
  ggplot(aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), color = "blue", alpha = .5) + 
  theme(legend.position = "bottom")

```

```{r}

pulse_df=
  haven::read_sas("~data/public_pulse_data.sas7bdat") |> 
  janitor::clean_names()

```
****pivot_longer(bl:12m....) mutate(visit=fct_inorder(visit))**

```{r}
weather_df |>
  select(name, tmax, tmin) |> 
  pivot_longer(
    tmax:tmin,
    names_to = "observation", 
    values_to = "temp") |> 
  ggplot(aes(x = temp, fill = observation)) +
  geom_density(alpha = .5) + 
  facet_grid(~name) + 
  viridis::scale_fill_viridis(discrete = TRUE)
```
pivot longer, 
group by 


```{r}

pups_df=
  read_csv("data/FAS_pups.csv", na=c("NA", ".", ""), skip=3) |> 
  janitor::clean_names() |> 
  mutate(sex=case_match(sex, 1~"male",
                        2~"Female"))

litters_df=
  read_csv("data/FAS_litters.csv", na=c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  separate(group, into=c("dose", "tx_day"), sep=3)


fas_df=
  left_join(pups_df, litters_df, by="litter_number")

fas_df |> 
  select(pd_ears:tx_day) |> 
  pivot_longer(
    pd_ears:pd_walk,
    names_to="outcome",
    values_to = "pn_day"
  ) |> 
  
  mutate(outcome=fct_reorder(outcome, pn_day)) |> 
  
  
  ggplot(aes(x=dose, y=pn_day))+
  geom_violin()+
  facet_grid(tx_day~outcome)

```


